# permissions for end users to view clusterpullsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterpullsecret-viewer-role
rules:
- apiGroups:
  - ops.alexellis.io
  resources:
  - clusterpullsecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ops.alexellis.io
  resources:
  - clusterpullsecrets/status
  verbs:
  - get
