# permissions for end users to edit clusterpullsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterpullsecret-editor-role
rules:
- apiGroups:
  - ops.alexellis.io
  resources:
  - clusterpullsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ops.alexellis.io
  resources:
  - clusterpullsecrets/status
  verbs:
  - get
