apiVersion: ops.alexellis.io/v1
kind: ClusterPullSecret
metadata:
  name: dockerhub
spec:
# See README.md for how to create the secret below
  secretRef:
    name: registry-creds-secret
    namespace: kube-system
